### ISSUE TITLE
یونیتی در لینوکس

### ISSUE THREAD

**Issue by Revisto** [asajadi84/unitycorn#1]
سلام . آموزش ها خیلی عالیه و بهتر و مهمتر از همه اوپن سورس و رایگان بودنشونه.
یه پیشنهاد داشتم. میتونید آموزشی هم بزارید که چجوری کارای اولیه )نصب یونیتی و سی شارپ( در لینوکس )اوبنتو( رو انجام بدیم.

**Comment by asajadi84** [comment]
سلام. ممنون از نظرتون.
با وجود این که یونیتی برای لینوکس هم عرضه شده (و دو سه سالی هم از انتشار نسخه‌های بتا میگذره) اما نسخه لینوکس به پایداری لازم نرسیده و با وجود این که من خودم اوبونتو رو برای کدنویسی نسبت به ویندوز ترجیح میدم اما «فعلا» بهتره برای بازیسازی یونیتی از ویندوز یا مک استفاده کنید.
ما هم منتظر هستیم که لینوکس توی جامعه یونیتی پررنگ‌تر بشه و امیدواریم اون روز هر چه زودتر برسه تا آموزش‌های مرتبطش رو اضافه کنیم.
